### PR TITLE
Adding iPhone 8 support *experimental*

### PR DESCRIPTION
**Pull request by narcyzzo**
Hello, i added _**iPhone 8 10,4**_ support with **12.3.1** keys for **ibss** and **ibec**, script has finished work but device **does not booting** after sending files via irecovery <***stay in recovery mode***> if u can and want, try to look into this issue, i can test everything for u related to _**iPhone 8 10,4**_ 
**[ I testing dowgrading to 13.1.2 from 13.3.1 ]**

### CODE REVIEW

**Comment by narcyzzo** [comment]
i also having this output running < **irecovery -s** > when phone stay in recovery mode after sending boot files : 
https://pastebin.com/WgZeeLsM

**Comment by narcyzzo** [comment]
WHAT THE FUCK I booted it thetered with checkra1n this command **_checkra1n -c -V -s -v_**

**Comment by narcyzzo** [comment]
Dude it booting without any issues with Checkra1n thetered, wtf im done :D

**Comment by Xoloth** [comment]
You're a legend. I was trying for 2 days with this script then I saw your comment. Now I use checkra1n to boot my device. Thanks!

**Comment by narcyzzo** [comment]
enjoy dude :D what device and ios?

**Comment by Xoloth** [comment]
iPhone 7 13.1.3. Its working fine but no wifi. I dont know how to fix it.

**Comment by MatthewPierson** [comment]
You will have broken Wifi if you don’t boot with PyBoot. I don’t recommend using checkra1n to boot

**Comment by Xoloth** [comment]
I want to use PyBoot but its not working. Its giving me some errors about python and libirecovery. I posted logs at issues page.

**Comment by narcyzzo** [comment]
from what iOS u downgraded? when im downgraded from 13.3.1 to 13.2.3 and booted with checkra1n all works fine, wifi too, but now, when i downgraded from futuredrestored 13.3 to 13.0 i have not working wifi too, so its not checkra1n related but sep compability ;), also we must boot with checkra1n coz pyboot not booting device, stucking at recovery mode, check what i write up :)

**Comment by Xoloth** [comment]
I downgraded from 13.3.1 to 13.1.3. Which version did you use? It just says "checking if the device is ready" when I use -c -V -v boot args.

**Comment by narcyzzo** [comment]
latest 0.9.8 , always work for me

**Comment by narcyzzo** [comment]
@MatthewPierson  u say booting with checkra1n causing wifi not working, i tested downgrading 13.3.1 to 13.2.3 booted tethered with checkra1n and i dont have any issue, wifi working, all working fine, then i futurerestore to 13.3 and downgrade to 13.0( due to succesion dont restoring kernel and i wanted try u0 to jailbreak[succesful]) and now i have wifi not working, i think it is related to sep not checkra1n

**Pull request closed without merging**
