### PR TITLE
[WIP] A11 support

### PR DESCRIPTION
**Pull request by M1staAwesome**
iBoot64Patcher compiled with Ralph's [liboffsetfinder64](https://github.com/ralph0045/liboffsetfinder64) can patch the A11 bootchain fine. Also, after iBSS and iBEC are sent, iBEC needs to be sent and jumped to again with `go` on A10/A11. Not working currently.

### CODE REVIEW

**Comment by MatthewPierson** [comment]
Have you tested this? Doesn't work for me, even with some modifications

**Comment by narcyzzo** [comment]
this work patching 13.1.3 bootchain but not with 13.4.1 i can test some of my iPhone 8 10,4

**Comment by M1staAwesome** [comment]
> Have you tested this? Doesn't work for me, even with some modifications

where exactly does it fail for you?
i was planning on testing with my own device but got what I think is a seperate issue of PyBoot, where either PyBoot chooses the incorrect device model (when trying to test on my A10 device, PyBoot extracts the d10ap DeviceTree instead of the d101ap DeviceTree (the other d10 components work with d101ap but the DeviceTree needs to be for the correct model.), or it gives me a prompt to choose which model my iPhone is, and neither is correct (e.g. my A11 device is d21ap, and PyBoot prompts me if my device is either d111ap or d11ap).

**Comment by narcyzzo** [comment]
@M1staAwesome  u try this ibootpatcher on any A11 device? u got tether boot on it? i have problem with patching the iPhone 8 10,4 bootchain

**Comment by M1staAwesome** [comment]
> @M1staAwesome u try this ibootpatcher on any A11 device? u got tether boot on it? i have problem with patching the iPhone 8 10,4 bootchain

i've verbose booted + booted a custom ramdisk with the iBoot64Patcher bundled, it should work

**Comment by MatthewPierson** [comment]
@M1staAwesome what devices/iOS versions have you had this work with (even manually)? For when you do it manually, can you give a step by step of what you did to ensure that I don't have issues in the process for PyBoot.

**Comment by narcyzzo** [comment]
i also patched bootchain succesfully and got verbose boot, try divise, device booting but kernel panic at _apple keystore sks timeuot strike 0_ , pls check dm on twitter @narcyzz0

**Comment by M1staAwesome** [comment]
> @M1staAwesome what devices/iOS versions have you had this work with (even manually)? For when you do it manually, can you give a step by step of what you did to ensure that I don't have issues in the process for PyBoot.

@MatthewPierson I've verbose booted an iPhone 8 Plus on 13.3, and also helped @narcyzzo with booting his iPhone 8 on 13.4.1.

My process is this:
-  Decrypt & extract iBSS/iBEC, and patch with an iBoot64Patcher compiled with [this](https://github.com/Ralph0045/liboffsetfinder64) fork of liboffsetfinder64 (The iBoot64Patcher on my fork is statically compiled, so you should be able to use it fine). iBEC has `rd=disk0s1sX -v` boot-args.
- Extract devicetree and patch with Ralph's [dtree_patcher](https://github.com/Ralph0045/dtree_patcher)
- Sign devicetree, trustcache, and kernel (and also changing to their restore tags)
- Pwn device with akayn's fork of ipwndfu and remove signature checks
- Send iBSS and iBEC
- Send iBEC one more time, then jump to it with `go`
- Send devicetree and trustcache, loading them after sending them (not sure if the aopfw is needed, but I haven't needed to use it ¯\_(ツ)_/¯)
- Send kernel, and boot.

**Comment by MatthewPierson** [comment]
@narcyzzo Did you have a passcode on the main os? If so remove it then try again, having a passcode on the main OS will cause issues when booting the second one. 

@M1staAwesome Strange, that's the same process that I use in PyBoot. I might give it a go manually myself later today, just to be sure. With the `sks timeout strike 0` issue, do you have a passcode on either OS? If possible could one or both of you show an image/video of the device verbose booting and panicking?

**Comment by narcyzzo** [comment]
@MatthewPierson  Yes, i have passcode on my main iOS, i dont try with disabled, and Yes i have a video i can give it to u when i woke up, just going sleep now, where i can send it?

**Comment by MatthewPierson** [comment]
@narcyzzo You can DM it to me on twitter. I bet that having the passcode on the main OS is the issue though, I know for a fact that it breaks 11.x and 12.x dualboots, so I assume it's the same for 13.x

**Comment by narcyzzo** [comment]
Hm, but @M1staAwesome  have the same issue just with try to verbose boot, So passcode still be the case?

**Comment by M1staAwesome** [comment]
@MatthewPierson I have a password on my main OS, but i'm also not dualbooting so I don't see why that'd be an issue. I'll attempt w/ no password on another device whenever I can.

**Comment by MatthewPierson** [comment]
@M1staAwesome @narcyzzo I have gotten this fork working now, it boots my A11 device but I am now getting the same sks timeout strike error. Now that I can reproduce this, I will look into finding a way to fix it

**Comment by narcyzzo** [comment]
just pls go to twitter, i got it working too, just disable passcode and it booted, but home, wifi not working

**Comment by M1staAwesome** [comment]
gonna close this for now, since a version of PyBoot with (partially) working A10/A11 support is now out

**Pull request closed without merging**
